//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xrm.Typed.Entities
{
	
	
	#region 
	static
	/// <summary>
	/// A component dependency in CRM.
	/// </summary>
	public partial class DependencyLogicalNames
	{
		
		public const string dependencyid = "dependencyid";
		
		public const string dependencytype = "dependencytype";
		
		public const string dependentcomponentbasesolutionid = "dependentcomponentbasesolutionid";
		
		public const string dependentcomponentnodeid = "dependentcomponentnodeid";
		
		public const string dependentcomponentobjectid = "dependentcomponentobjectid";
		
		public const string dependentcomponentparentid = "dependentcomponentparentid";
		
		public const string dependentcomponenttype = "dependentcomponenttype";
		
		public const string requiredcomponentbasesolutionid = "requiredcomponentbasesolutionid";
		
		public const string requiredcomponentintroducedversion = "requiredcomponentintroducedversion";
		
		public const string requiredcomponentnodeid = "requiredcomponentnodeid";
		
		public const string requiredcomponentobjectid = "requiredcomponentobjectid";
		
		public const string requiredcomponentparentid = "requiredcomponentparentid";
		
		public const string requiredcomponenttype = "requiredcomponenttype";
	}
	#endregion
	
	#region 
	static
	/// <summary>
	/// Assembly that contains one or more plug-in types.
	/// </summary>
	public partial class PluginAssemblyLogicalNames
	{
		
		public const string componentstate = "componentstate";
		
		public const string content = "content";
		
		public const string createdby = "createdby";
		
		public const string createdon = "createdon";
		
		public const string createdonbehalfby = "createdonbehalfby";
		
		public const string culture = "culture";
		
		public const string customizationlevel = "customizationlevel";
		
		public const string description = "description";
		
		public const string introducedversion = "introducedversion";
		
		public const string iscustomizable = "iscustomizable";
		
		public const string ishidden = "ishidden";
		
		public const string ismanaged = "ismanaged";
		
		public const string isolationmode = "isolationmode";
		
		public const string major = "major";
		
		public const string minor = "minor";
		
		public const string modifiedby = "modifiedby";
		
		public const string modifiedon = "modifiedon";
		
		public const string modifiedonbehalfby = "modifiedonbehalfby";
		
		public const string name = "name";
		
		public const string organizationid = "organizationid";
		
		public const string overwritetime = "overwritetime";
		
		public const string path = "path";
		
		public const string pluginassemblyid = "pluginassemblyid";
		
		public const string pluginassemblyidunique = "pluginassemblyidunique";
		
		public const string publickeytoken = "publickeytoken";
		
		public const string solutionid = "solutionid";
		
		public const string sourcehash = "sourcehash";
		
		public const string sourcetype = "sourcetype";
		
		public const string version = "version";
		
		public const string versionnumber = "versionnumber";
	}
	#endregion
	
	#region 
	static
	/// <summary>
	/// Type that inherits from the IPlugin interface and is contained within a plug-in assembly.
	/// </summary>
	public partial class PluginTypeLogicalNames
	{
		
		public const string assemblyname = "assemblyname";
		
		public const string componentstate = "componentstate";
		
		public const string createdby = "createdby";
		
		public const string createdon = "createdon";
		
		public const string createdonbehalfby = "createdonbehalfby";
		
		public const string culture = "culture";
		
		public const string customizationlevel = "customizationlevel";
		
		public const string customworkflowactivityinfo = "customworkflowactivityinfo";
		
		public const string description = "description";
		
		public const string friendlyname = "friendlyname";
		
		public const string ismanaged = "ismanaged";
		
		public const string isworkflowactivity = "isworkflowactivity";
		
		public const string major = "major";
		
		public const string minor = "minor";
		
		public const string modifiedby = "modifiedby";
		
		public const string modifiedon = "modifiedon";
		
		public const string modifiedonbehalfby = "modifiedonbehalfby";
		
		public const string name = "name";
		
		public const string organizationid = "organizationid";
		
		public const string overwritetime = "overwritetime";
		
		public const string pluginassemblyid = "pluginassemblyid";
		
		public const string plugintypeid = "plugintypeid";
		
		public const string plugintypeidunique = "plugintypeidunique";
		
		public const string publickeytoken = "publickeytoken";
		
		public const string solutionid = "solutionid";
		
		public const string typename = "typename";
		
		public const string version = "version";
		
		public const string versionnumber = "versionnumber";
		
		public const string workflowactivitygroupname = "workflowactivitygroupname";
	}
	#endregion
	
	#region 
	static
	/// <summary>
	/// A publisher of a CRM solution.
	/// </summary>
	public partial class PublisherLogicalNames
	{
		
		public const string address1_addressid = "address1_addressid";
		
		public const string address1_addresstypecode = "address1_addresstypecode";
		
		public const string address1_city = "address1_city";
		
		public const string address1_country = "address1_country";
		
		public const string address1_county = "address1_county";
		
		public const string address1_fax = "address1_fax";
		
		public const string address1_latitude = "address1_latitude";
		
		public const string address1_line1 = "address1_line1";
		
		public const string address1_line2 = "address1_line2";
		
		public const string address1_line3 = "address1_line3";
		
		public const string address1_longitude = "address1_longitude";
		
		public const string address1_name = "address1_name";
		
		public const string address1_postalcode = "address1_postalcode";
		
		public const string address1_postofficebox = "address1_postofficebox";
		
		public const string address1_shippingmethodcode = "address1_shippingmethodcode";
		
		public const string address1_stateorprovince = "address1_stateorprovince";
		
		public const string address1_telephone1 = "address1_telephone1";
		
		public const string address1_telephone2 = "address1_telephone2";
		
		public const string address1_telephone3 = "address1_telephone3";
		
		public const string address1_upszone = "address1_upszone";
		
		public const string address1_utcoffset = "address1_utcoffset";
		
		public const string address2_addressid = "address2_addressid";
		
		public const string address2_addresstypecode = "address2_addresstypecode";
		
		public const string address2_city = "address2_city";
		
		public const string address2_country = "address2_country";
		
		public const string address2_county = "address2_county";
		
		public const string address2_fax = "address2_fax";
		
		public const string address2_latitude = "address2_latitude";
		
		public const string address2_line1 = "address2_line1";
		
		public const string address2_line2 = "address2_line2";
		
		public const string address2_line3 = "address2_line3";
		
		public const string address2_longitude = "address2_longitude";
		
		public const string address2_name = "address2_name";
		
		public const string address2_postalcode = "address2_postalcode";
		
		public const string address2_postofficebox = "address2_postofficebox";
		
		public const string address2_shippingmethodcode = "address2_shippingmethodcode";
		
		public const string address2_stateorprovince = "address2_stateorprovince";
		
		public const string address2_telephone1 = "address2_telephone1";
		
		public const string address2_telephone2 = "address2_telephone2";
		
		public const string address2_telephone3 = "address2_telephone3";
		
		public const string address2_upszone = "address2_upszone";
		
		public const string address2_utcoffset = "address2_utcoffset";
		
		public const string createdby = "createdby";
		
		public const string createdon = "createdon";
		
		public const string createdonbehalfby = "createdonbehalfby";
		
		public const string customizationoptionvalueprefix = "customizationoptionvalueprefix";
		
		public const string customizationprefix = "customizationprefix";
		
		public const string description = "description";
		
		public const string emailaddress = "emailaddress";
		
		public const string entityimage = "entityimage";
		
		public const string entityimage_timestamp = "entityimage_timestamp";
		
		public const string entityimage_url = "entityimage_url";
		
		public const string entityimageid = "entityimageid";
		
		public const string friendlyname = "friendlyname";
		
		public const string isreadonly = "isreadonly";
		
		public const string modifiedby = "modifiedby";
		
		public const string modifiedon = "modifiedon";
		
		public const string modifiedonbehalfby = "modifiedonbehalfby";
		
		public const string organizationid = "organizationid";
		
		public const string pinpointpublisherdefaultlocale = "pinpointpublisherdefaultlocale";
		
		public const string pinpointpublisherid = "pinpointpublisherid";
		
		public const string publisherid = "publisherid";
		
		public const string supportingwebsiteurl = "supportingwebsiteurl";
		
		public const string uniquename = "uniquename";
		
		public const string versionnumber = "versionnumber";
	}
	#endregion
	
	#region 
	static
	/// <summary>
	/// A solution which contains CRM customizations.
	/// </summary>
	public partial class SolutionLogicalNames
	{
		
		public const string configurationpageid = "configurationpageid";
		
		public const string createdby = "createdby";
		
		public const string createdon = "createdon";
		
		public const string createdonbehalfby = "createdonbehalfby";
		
		public const string description = "description";
		
		public const string friendlyname = "friendlyname";
		
		public const string installedon = "installedon";
		
		public const string ismanaged = "ismanaged";
		
		public const string isvisible = "isvisible";
		
		public const string modifiedby = "modifiedby";
		
		public const string modifiedon = "modifiedon";
		
		public const string modifiedonbehalfby = "modifiedonbehalfby";
		
		public const string organizationid = "organizationid";
		
		public const string parentsolutionid = "parentsolutionid";
		
		public const string pinpointassetid = "pinpointassetid";
		
		public const string pinpointpublisherid = "pinpointpublisherid";
		
		public const string pinpointsolutiondefaultlocale = "pinpointsolutiondefaultlocale";
		
		public const string pinpointsolutionid = "pinpointsolutionid";
		
		public const string publisherid = "publisherid";
		
		public const string solutionid = "solutionid";
		
		public const string solutionpackageversion = "solutionpackageversion";
		
		public const string solutiontype = "solutiontype";
		
		public const string uniquename = "uniquename";
		
		public const string version = "version";
		
		public const string versionnumber = "versionnumber";
	}
	#endregion
	
	#region 
	static
	/// <summary>
	/// A component of a CRM solution.
	/// </summary>
	public partial class SolutionComponentLogicalNames
	{
		
		public const string componenttype = "componenttype";
		
		public const string createdby = "createdby";
		
		public const string createdon = "createdon";
		
		public const string createdonbehalfby = "createdonbehalfby";
		
		public const string ismetadata = "ismetadata";
		
		public const string modifiedby = "modifiedby";
		
		public const string modifiedon = "modifiedon";
		
		public const string modifiedonbehalfby = "modifiedonbehalfby";
		
		public const string objectid = "objectid";
		
		public const string rootcomponentbehavior = "rootcomponentbehavior";
		
		public const string rootsolutioncomponentid = "rootsolutioncomponentid";
		
		public const string solutioncomponentid = "solutioncomponentid";
		
		public const string solutionid = "solutionid";
		
		public const string versionnumber = "versionnumber";
	}
	#endregion
	
	#region 
	static
	/// <summary>
	/// Data equivalent to files used in Web development. Web resources provide client-side components that are used to provide custom user interface elements.
	/// </summary>
	public partial class WebResourceLogicalNames
	{
		
		public const string canbedeleted = "canbedeleted";
		
		public const string componentstate = "componentstate";
		
		public const string content = "content";
		
		public const string createdby = "createdby";
		
		public const string createdon = "createdon";
		
		public const string createdonbehalfby = "createdonbehalfby";
		
		public const string dependencyxml = "dependencyxml";
		
		public const string description = "description";
		
		public const string displayname = "displayname";
		
		public const string introducedversion = "introducedversion";
		
		public const string isavailableformobileoffline = "isavailableformobileoffline";
		
		public const string iscustomizable = "iscustomizable";
		
		public const string isenabledformobileclient = "isenabledformobileclient";
		
		public const string ishidden = "ishidden";
		
		public const string ismanaged = "ismanaged";
		
		public const string languagecode = "languagecode";
		
		public const string modifiedby = "modifiedby";
		
		public const string modifiedon = "modifiedon";
		
		public const string modifiedonbehalfby = "modifiedonbehalfby";
		
		public const string name = "name";
		
		public const string organizationid = "organizationid";
		
		public const string overwritetime = "overwritetime";
		
		public const string silverlightversion = "silverlightversion";
		
		public const string solutionid = "solutionid";
		
		public const string versionnumber = "versionnumber";
		
		public const string webresourceid = "webresourceid";
		
		public const string webresourceidunique = "webresourceidunique";
		
		public const string webresourcetype = "webresourcetype";
	}
	#endregion
}
